[package]
name = "hhlib-sys"
version = "0.1.0"
authors = ["Max Tyler <maxastyler@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.49"

[dependencies]
num-derive = "0.2"
num-traits = "0.2"
num = "0.2"