[package]
name = "rusty-hhpython"
version = "0.1.0"
authors = ["Max Tyler <maxastyler@gmail.com>"]
edition = "2018"
crate-type = "cdylib"

[dependencies]
cpython = { version = "0.2.1", features = ["extension-module"]}
hhlib-sys = { path = '../hhlib-sys' }
